<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.RabbitMq" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Services\Shipping\Deliver.Shipping.Api\Deliver.Shipping.Api.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Shared\*.cs" LinkBase="Shared" />
    <Compile Include="..\Shared\Web\*.cs" LinkBase="Shared" />
  </ItemGroup>
</Project>
