<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.RabbitMq" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="EFCore.NamingConventions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks\Deliver.Messaging\Deliver.Messaging.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Shared\*.cs" LinkBase="Shared" />
  </ItemGroup>
</Project>
